{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "resource-operator.fullname" . }}-mutating-webhook
  labels:
    {{- include "resource-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.certificate.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "resource-operator.certName" . }}
  {{- end }}
webhooks:
  - name: workload-injection.resources.xfsc.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    matchPolicy: Equivalent
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "resource-operator.webhookServiceName" . }}
        path: /mutate-workloads
        port: {{ .Values.webhook.servicePort }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      {{- toYaml .Values.webhook.namespaceSelector | nindent 6 }}
{{- end }}
