apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource-operator.fullname" . }}-modules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resource-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  modules.yaml: |
{{ toYaml .Values.moduleConfig | nindent 4 }}
