apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xsfc-resource-operator-serving-cert
  namespace: xsfc-system
spec:
  dnsNames:
    - xsfc-resource-operator-webhook.xsfc-system.svc
    - xsfc-resource-operator-webhook.xsfc-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: xsfc-resource-operator-selfsigned
  secretName: xsfc-resource-operator-webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: xsfc-resource-operator-selfsigned
  namespace: xsfc-system
spec:
  selfSigned: {}
