apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: xsfc-resource-operator-mutating-webhook
  annotations:
    cert-manager.io/inject-ca-from: xsfc-system/xsfc-resource-operator-serving-cert
webhooks:
  - name: workload-injection.resources.xfsc.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Equivalent
    clientConfig:
      service:
        namespace: xsfc-system
        name: xsfc-resource-operator-webhook
        path: /mutate-workloads
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments", "statefulsets", "daemonsets"]
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["batch"]
        apiVersions: ["v1"]
        resources: ["jobs", "cronjobs"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "kube-public", "kube-node-lease", "xsfc-system"]
