apiVersion: v1
kind: Service
metadata:
  name: xsfc-resource-operator-webhook
  namespace: xsfc-system
spec:
  selector:
    app: xsfc-resource-operator
  ports:
    - name: https
      port: 443
      targetPort: 9443
