apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xsfc-resource-operator
rules:
  - apiGroups: ["resources.xfsc.io"]
    resources: ["resourceproviders", "resourcebindings", "resourcebindings/status", "resourceproviders/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
