//go:build !ignore_autogenerated

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *ResourceProvider) DeepCopyObject() runtime.Object {
	out := new(ResourceProvider)
	*out = *in
	return out
}
func (in *ResourceProviderList) DeepCopyObject() runtime.Object {
	out := new(ResourceProviderList)
	*out = *in
	return out
}
