//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ResourceProvider) DeepCopyInto(out *ResourceProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ResourceProvider) DeepCopy() *ResourceProvider {
	if in == nil {
		return nil
	}
	out := new(ResourceProvider)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceProvider) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *ResourceProviderList) DeepCopyInto(out *ResourceProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ResourceProvider, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *ResourceProviderList) DeepCopy() *ResourceProviderList {
	if in == nil {
		return nil
	}
	out := new(ResourceProviderList)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceProviderList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *ResourceProviderSpec) DeepCopyInto(out *ResourceProviderSpec) {
	*out = *in
	in.Allow.DeepCopyInto(&out.Allow)
	in.Outputs.DeepCopyInto(&out.Outputs)
	if in.AdminSecretRef != nil {
		out.AdminSecretRef = new(NamespacedSecretRef)
		*out.AdminSecretRef = *in.AdminSecretRef
	}
}

func (in *ProviderAllowSpec) DeepCopyInto(out *ProviderAllowSpec) {
	*out = *in
	if in.Namespaces != nil {
		out.Namespaces = append([]string(nil), in.Namespaces...)
	}
	if in.Selector != nil {
		out.Selector = make(map[string]string, len(in.Selector))
		for k, v := range in.Selector {
			out.Selector[k] = v
		}
	}
}

func (in *ProviderOutputs) DeepCopyInto(out *ProviderOutputs) {
	*out = *in
	if in.Env != nil {
		out.Env = make(map[string]string, len(in.Env))
		for k, v := range in.Env {
			out.Env[k] = v
		}
	}
	if in.ExternalSecrets != nil {
		out.ExternalSecrets = make([]ExternalSecretOutput, len(in.ExternalSecrets))
		for i := range in.ExternalSecrets {
			in.ExternalSecrets[i].DeepCopyInto(&out.ExternalSecrets[i])
		}
	}
}

func (in *ExternalSecretOutput) DeepCopyInto(out *ExternalSecretOutput) {
	*out = *in
	if in.Data != nil {
		out.Data = append([]ExternalSecretKey(nil), in.Data...)
	}
}

func (in *ResourceProviderStatus) DeepCopyInto(out *ResourceProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *ResourceClaim) DeepCopyInto(out *ResourceClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *ResourceClaim) DeepCopy() *ResourceClaim {
	if in == nil {
		return nil
	}
	out := new(ResourceClaim)
	in.DeepCopyInto(out)
	return out
}
func (in *ResourceClaim) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ResourceClaimList) DeepCopyInto(out *ResourceClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ResourceClaim, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ResourceClaimList) DeepCopy() *ResourceClaimList {
	if in == nil {
		return nil
	}
	out := new(ResourceClaimList)
	in.DeepCopyInto(out)
	return out
}
func (in *ResourceClaimList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *ResourceClaimSpec) DeepCopyInto(out *ResourceClaimSpec) {
	*out = *in
	if in.ProviderRef != nil {
		out.ProviderRef = new(LocalProviderRef)
		*out.ProviderRef = *in.ProviderRef
	}
	if in.ProviderSelector != nil {
		out.ProviderSelector = in.ProviderSelector.DeepCopy()
	}
	in.Parameters.DeepCopyInto(&out.Parameters)
}
func (in *ResourceClaimStatus) DeepCopyInto(out *ResourceClaimStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}
