apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2
spec:
  replicas: 1

  selector:
    matchLabels:
      app: hello

  template:
    metadata:
      labels:
        app: hello
      annotations:
        inject.xfsc.io/enabled: "true"
        inject.xfsc.io/needs: "hello"

    spec:
      containers:
        - name: hello
          image: busybox
          command:
            - sh
            - -c
            - |
              env
              sleep 3600