apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallet-api-redis-eso
  namespace: tenant-a
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: wallet-api-redis
    creationPolicy: Owner
  data:
    - secretKey: REDIS_USERNAME
      remoteRef:
        key: tenants/tenant-a/redis/wallet-api
        property: username
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: tenants/tenant-a/redis/wallet-api
        property: password
