apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-api
  namespace: tenant-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-api
  template:
    metadata:
      labels:
        app: wallet-api
      annotations:
        inject.xfsc.io/enabled: "true"
        inject.xfsc.io/needs: "redis"
    spec:
      containers:
        - name: app
          image: nginx:1.27
