apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xsfc-resource-operator
  namespace: xsfc-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: xsfc-resource-operator
  namespaceSelector:
    matchNames:
      - xsfc-system
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
